# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for USB Power Delivery drivers
#

# obj-$(CONFIG_USB_SYBC_BQ2589X)	+= bq2589x_dual.o
obj-$(CONFIG_USB_SY_MASTER)	+= symaster.o sy_dev_class.o

obj-$(CONFIG_USB_SY_BC7D)	+= bc7d.o

obj-$(CONFIG_USB_SY_PD7E)	+= pd7e.o

obj-$(CONFIG_USB_SY_UF7F)	+= ufcs7f.o