obj-$(CONFIG_RT_REGMAP)		+= sp_rt-regmap.o

obj-$(CONFIG_SWITCH)		+= sp_switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= sp_switch_gpio.o
obj-$(CONFIG_SWITCH_HD3SS460)		+= sp_switch_hd3ss460.o

obj-$(CONFIG_DUAL_ROLE_USB_INTF)	+= sp_class-dual-role.o sp_tcpci_dual_role.o


obj-$(CONFIG_TCPC_RT1711H)		+= sp_tcpc_rt1711h.o

obj-$(CONFIG_TCPC_CLASS)		+= sp_tcpci_core.o sp_tcpci_typec.o sp_tcpci_alert.o \
					   sp_tcpci_timer.o sp_tcpm.o sp_tcpm_legacy.o sp_tcpm_block.o sp_pd_dbg_info.o

obj-$(CONFIG_USB_POWER_DELIVERY)	+= sp_tcpci_event.o \
					   sp_pd_core.o sp_pd_policy_engine.o sp_pd_process_evt.o sp_pd_dpm_core.o \
					   sp_pd_process_evt_snk.o sp_pd_process_evt_src.o sp_pd_process_evt_vdm.o \
					   sp_pd_process_evt_drs.o sp_pd_process_evt_prs.o sp_pd_process_evt_vcs.o \
					   sp_pd_policy_engine_src.o sp_pd_policy_engine_snk.o sp_pd_policy_engine_ufp.o \
					   sp_pd_policy_engine_vcs.o sp_pd_dpm_uvdm.o sp_pd_process_evt_dbg.o \
					   sp_pd_policy_engine_dbg.o sp_pd_policy_engine_dfp.o sp_pd_policy_engine_dr.o \
					   sp_pd_policy_engine_drs.o sp_pd_policy_engine_prs.o sp_pd_dpm_alt_mode_dp.o \
					   sp_pd_dpm_pdo_select.o










